IntonationProject/config/routes.rb
Rails.application.routes.draw do
  get 'recording/index'

  get 'home_page/index'

  resources :quizzes

  get "/pages/:page" => "pages#show"
  root "home#show"
end

IntonationProject/app/models/quiz.rb
class Quiz < ActiveRecord::Base
	validates :first_name, presence: true
	validates :last_name, presence: true
	validates :age, presence: true
	validates :height_feet, presence: true
	validates :height_inches, presence: true
	validates :gender, presence: true
	validates :native_mandarin, presence: true
	validates :native_english, presence: true
	validates :exp, presence: true
end

IntonationProject/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

IntonationProject/app/controllers/home_controller.rb
class HomeController < ApplicationController
	def show
		render template:"/index"
	end
end

IntonationProject/app/controllers/home_page_controller.rb
class HomePageController < ApplicationController
  def index
  end
end

IntonationProject/app/controllers/pages_controller.rb
class PagesController < ApplicationController
	def show
		render template: "pages/#{params[:page]}"
	end
end

IntonationProject/app/controllers/quizzes_controller.rb
class QuizzesController < ApplicationController
  before_action :set_quiz, only: [:show, :edit, :update, :destroy]

  # GET /quizzes
  # GET /quizzes.json
  def index
    @quizzes = Quiz.all
  end

  # GET /quizzes/1
  # GET /quizzes/1.json
  def show
  end

  # GET /quizzes/new
  def new
    @quiz = Quiz.new
  end

  # GET /quizzes/1/edit
  def edit
  end

  # POST /quizzes
  # POST /quizzes.json
  def create
    @quiz = Quiz.new(quiz_params)

    respond_to do |format|
      if @quiz.save
        format.html { redirect_to @quiz, notice: 'Quiz was successfully created.' }
        format.json { render :show, status: :created, location: @quiz }
      else
        format.html { render :new }
        format.json { render json: @quiz.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /quizzes/1
  # PATCH/PUT /quizzes/1.json
  def update
    respond_to do |format|
      if @quiz.update(quiz_params)
        format.html { redirect_to @quiz, notice: 'Quiz was successfully updated.' }
        format.json { render :show, status: :ok, location: @quiz }
      else
        format.html { render :edit }
        format.json { render json: @quiz.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /quizzes/1
  # DELETE /quizzes/1.json
  def destroy
    @quiz.destroy
    respond_to do |format|
      format.html { redirect_to quizzes_url, notice: 'Quiz was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_quiz
      @quiz = Quiz.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def quiz_params
      params.require(:quiz).permit(:first_name, :last_name, :age, :height_feet, :height_inches, :gender, :native_mandarin, :native_english, :exp)
    end
end

IntonationProject/app/controllers/recording_controller.rb
class RecordingController < ApplicationController
  def index
  end
end

IntonationProject/app/helpers/application_helper.rb
module ApplicationHelper
end

IntonationProject/app/helpers/home_page_helper.rb
module HomePageHelper
end

IntonationProject/app/helpers/quizzes_helper.rb
module QuizzesHelper
end

IntonationProject/app/helpers/recording_helper.rb
module RecordingHelper
end

IntonationProject/app/views/home_page/index.html.erb
<script>
	$(document).ready(function() {
		$('.ui.accordion').accordion();
	});
</script>

<style>
	.ui.secondary.vertical.menu {
		width: 100%;
	}

	.ui.card {
		width: 100%;
	}
</style>

<div class="ui padded grid">
	<div class="five wide column">
		<div class="ui one column grid">

			<div class="column">
				<div class="ui card">
					<div class="image">
						<img src="" alt="">
					</div>
					<div class="content">
						<a class="header">
							Your Name
						</a>
						<div class="meta">
							Volunteer
						</div>
					</div>
				</div>
			</div>

			<div class="column">
				<div class="ui styled fluid accordion">
					<div class="active title">
						Lesson 1
					</div>
					<div class="active content">
						<div class="ui secondary vertical menu">
							<a class="item">
								Exercise #1
							</a>
							<a class="item">
								Exercise #2
							</a>
							<a class="item">
								Exercise #3
							</a>
							<a class="item">
								Exercise #4
							</a>
						</div>
					</div>

					<div class="title">
						Lesson 2
					</div>
					<div class="content">
						<div class="ui secondary vertical menu">
							<a class="item">
								Exercise #1
							</a>
							<a class="item">
								Exercise #2
							</a>
							<a class="item">
								Exercise #3
							</a>
							<a class="item">
								Exercise #4
							</a>
						</div>
					</div>

					<div class="title">
						Lesson 3
					</div>
					<div class="content">
						<div class="ui secondary vertical menu">
							<a class="item">
								Exercise #1
							</a>
							<a class="item">
								Exercise #2
							</a>
							<a class="item">
								Exercise #3
							</a>
							<a class="item">
								Exercise #4
							</a>
						</div>
					</div>

					<div class="title">
						Lesson 4
					</div>
					<div class="content">
						<div class="ui secondary vertical menu">
							<a class="item">
								Exercise #1
							</a>
							<a class="item">
								Exercise #2
							</a>
							<a class="item">
								Exercise #3
							</a>
							<a class="item">
								Exercise #4
							</a>
						</div>
					</div>

					<div class="title">
						Lesson 5
					</div>
					<div class="content">
						<div class="ui secondary vertical menu">
							<a class="item">
								Exercise #1
							</a>
							<a class="item">
								Exercise #2
							</a>
							<a class="item">
								Exercise #3
							</a>
							<a class="item">
								Exercise #4
							</a>
						</div>
					</div>
				</div><!-- ui styled fluid accordion -->
			</div><!-- column -->

		</div><!-- ui grid -->
	</div><!-- five wide column -->

	<div class="eleven wide column">
		<div class="ui vertical segment">
		
			<h1 class="ui header">
				Hello! Welcome to your personal user page.
			</h1>

			<h3>app > views > home_page > index.html.erb</h3>

			Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.

			<br />
			<br />

			<a class="ui blue button" href="/recording/index">
				Click here for Recording Page
			</a>
		</div>
	</div>

</div>

IntonationProject/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Learn Mandarin Tones</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <!-- JQuery -->
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>

  <!-- Semantic UI -->
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/semantic-ui/1.11.8/semantic.min.css"/>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/semantic-ui/1.11.8/semantic.min.js"></script>
</head>
<body>

<div class="ui secondary menu">
  <a class="item" href="/">Home</a>
  <div class="right menu">
    <a class="item" href="/home_page/index">Login</a>
  </div>
</div>

<%= yield %>

</body>
</html>

IntonationProject/app/views/pages/index.html.erb
asdf

IntonationProject/app/views/quizzes/_form.html.erb
<%= form_for(@quiz) do |f| %>
  <% if @quiz.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@quiz.errors.count, "error") %> prohibited this quiz from being saved:</h2>

      <ul>
      <% @quiz.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<div class="ui centered segment">
  <div class="ui form">
    <div class="field">
      <%= f.label :first_name %><br>
      <%= f.text_field :first_name %>
    </div>
    <div class="field">
      <%= f.label :last_name %><br>
      <%= f.text_field :last_name %>
    </div>
    <div class="field">
      <%= f.label :age %><br>
      <%= f.number_field :age %>
    </div>
    <div class="field">
      <%= f.label :height_feet %><br>
      <%= f.number_field :height_feet %>
    </div>
    <div class="field">
      <%= f.label :height_inches %><br>
      <%= f.number_field :height_inches %>
    </div>
    <div class="field">
      <%= f.label :gender %><br>
      <%= f.text_field :gender %>
    </div>
    <div class="field">
      <%= f.label :native_mandarin %><br>
      <%= f.check_box :native_mandarin %>
    </div>
    <div class="field">
      <%= f.label :native_english %><br>
      <%= f.check_box :native_english %>
    </div>
    <div class="field">
      <%= f.label :exp %><br>
      <%= f.text_area :exp %>
    </div>
    <div class="actions">
      <%= f.submit %>
    </div>
  </div>
</div>
<% end %>

IntonationProject/app/views/quizzes/edit.html.erb
<h1>Editing Quiz</h1>

<%= render 'form' %>

<%= link_to 'Show', @quiz %> |
<%= link_to 'Back', quizzes_path %>

IntonationProject/app/views/quizzes/index.html.erb
<div class="ui center aligned one column grid">

<div class="column"
  <p id="notice"><%= notice %></p>
</div>

<div class="column">
  <h1>Listing Quizzes</h1>
</div>

<div class="column">
  <table class="ui padded table">
    <thead>
      <tr>
        <th>First name</th>
        <th>Last name</th>
        <th>Age</th>
        <th>Height feet</th>
        <th>Height inches</th>
        <th>Gender</th>
        <th>Native mandarin</th>
        <th>Native english</th>
        <th>Exp</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @quizzes.each do |quiz| %>
        <tr>
          <td><%= quiz.first_name %></td>
          <td><%= quiz.last_name %></td>
          <td><%= quiz.age %></td>
          <td><%= quiz.height_feet %></td>
          <td><%= quiz.height_inches %></td>
          <td><%= quiz.gender %></td>
          <td><%= quiz.native_mandarin %></td>
          <td><%= quiz.native_english %></td>
          <td><%= quiz.exp %></td>
          <td><%= link_to 'Show', quiz, class: "ui blue button" %></td>
          <td><%= link_to 'Edit', edit_quiz_path(quiz), class: "ui yellow button" %></td>
          <td><%= link_to 'Destroy', quiz, method: :delete, data: { confirm: 'Are you sure?' }, class: "ui red button" %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

<br>

<div class="column">
  <%= link_to 'New Quiz', new_quiz_path, class: 'ui green button' %>
</div>

</div>

IntonationProject/app/views/quizzes/new.html.erb
<div class="ui center aligned one column grid">

<div class="column">
	<h1>New Quiz</h1>
</div>
<div class="eight wide column">
	<%= render 'form' %>
</div>

<div class="column">
	<%= link_to 'Back', quizzes_path, class: "ui grey button" %>
</div>
</div>

IntonationProject/app/views/quizzes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>First name:</strong>
  <%= @quiz.first_name %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @quiz.last_name %>
</p>

<p>
  <strong>Age:</strong>
  <%= @quiz.age %>
</p>

<p>
  <strong>Height feet:</strong>
  <%= @quiz.height_feet %>
</p>

<p>
  <strong>Height inches:</strong>
  <%= @quiz.height_inches %>
</p>

<p>
  <strong>Gender:</strong>
  <%= @quiz.gender %>
</p>

<p>
  <strong>Native mandarin:</strong>
  <%= @quiz.native_mandarin %>
</p>

<p>
  <strong>Native english:</strong>
  <%= @quiz.native_english %>
</p>

<p>
  <strong>Exp:</strong>
  <%= @quiz.exp %>
</p>

<%= link_to 'Edit', edit_quiz_path(@quiz) %> |
<%= link_to 'Back', quizzes_path %>

IntonationProject/app/views/recording/index.html.erb
<div class="ui one column padded centered grid">
	<div class="column">
		<h1>Recording page</h1>
	</div>
	<div class="column" style="background-color: pink;">
		app > views > recording > index.html.erb
	</div>
</div>